const express = require('express');
const swaggerJsDoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');
const app = express();
const PORT = 8080;

//Extended: https://swagger.io/specification/#infoObject
const swaggerOptions = {
    swaggerDefinition: {
        openapi: "3.0.0",
        info: {
            title: "FastTrack Dev Shirt API",
            description: "FastTrack Dev Shirts API Info",
            contact: {
                name: "Jamal B."
            },
            version: "1.0",
            //servers: ["http://localhost:8080"]
        },
        paths: {
            "/docs.json": {
                "get": {
                    "description": "Autogenerated",
                    "responses": {
                        "200": {
                            "description": "Successful Response Back ❤️!!"
                        }
                    }
                }
            },
        }
    },
    // ['.routes/*.js']
    apis: ["index.js"]
};
//This is the localhost configuration below
/*
const swaggerOptions = {
    swaggerDefinition: {
        openapi: "3.0.0",
        info: {
            title: "FastTrack Dev Shirt API",
            description: "FastTrack Dev Shirts API Info",
            contact: {
                name: "Jamal B."
            },
            version: "1.0",
            servers: ["http://localhost:8080"]
        }
    },
    // ['.routes/*.js']
    apis: ["index.js"]
};
*/


const swaggerDocs = swaggerJsDoc(swaggerOptions);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocs));

app.use(express.json())

// Routes
 /**
  * @swagger
  * /tshirt:
  *  get:
  *    description: List of FastTrack Tee Shirts Available
  *    responses:
  *      '200':
  *        description: Successful Response Back ❤️!!
  * /jacket:
  *  get:
  *    description: List of FastTrack Jackets Available
  *    responses:
  *      '200':
  *        description: Successful Response Back ❤️!!
  */

app.get('/docs.json', (req, res) =>
{
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerDocs);
})

app.get('/tshirt', (req, res) =>
{
    res.status(200).send({
        fta_dev_tshirt:'👕',
        size: 'large'
    })
});

app.get('/jacket', (req, res) =>
{
    res.status(200).send({
        jacket:'🧥',
        size: 'large'
    })
});

app.post('/tshirt/:id', (req, res) => {
    const {id} = req.params;
    const {logo} = req.body;

    if (!logo){
        res.status(418).send({message: 'We need a logo!'})
    }

    res.send({
        tshirt: `👕 with your ${logo} and ID of ${id}`,
    });

});


app.listen(
    PORT,
    () => console.log(`its alive on http://localhost:${PORT}`)
)
